//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartID { get; set; }
        public string PartName { get; set; }
        public string ModelNo { get; set; }
        public string Manufacturer { get; set; }
        public string PartDescription { get; set; }
    }
}
